### ISSUE TITLE
Way for plugins to self-document their hierarchy

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#291]
Allows wash to expose a schema of the hierarchy to document what the plugin provides. Use it to optimize `wash find`. This is also useful in understanding how plugins are structured when developing and using them.

- [x] Add schema description to core plugins (#321)
- [x] Implement `stree` (#325)
- [x] Optimize `-action` with `wash find` (#333)
- [x] Extend schema to include metadata content (#351)
- [x] Optimize `-meta` with `wash find`
- [x] Support external plugin schemas (#364)
- [x] Update documentation (including adding notes about the `stree` command) (#365)

**Comment by ekinanp** [comment]
The goal here is something like
```
$ schema aws
aws
    profile
        resources
            ec2
                instances
                    instance
                        metadata.json
                        consoleLog
            s3
                bucket
                    object
                    objectPrefix
                        object
                        objectPrefix    
```

i.e., given an arbitrary entry's path, the `schema` command would list the schema of the FS rooted at that entry. For example, if given an EC2 instance, then `schema` would list something like:
```
$ schema aws/demo/resources/ec2/instances/foo
aws/demo/resources/ec2/instances/foo
    metadata.json
    consoleLog
```

**Comment by ekinanp** [comment]
Some TODOs that need to be finished after https://github.com/puppetlabs/wash/pull/321 is merged.

- [ ] Implement `stree`
- [ ] Optimize some parts of `wash find`
- [ ] Support external plugin schemas
- [ ] Update documentation

**Comment by MikaelSmith** [comment]
We could include a note that stree can be useful for visualizing how Wash sees your plugin as you write it.
