### ISSUE TITLE
Add GCP serverless resources

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#576]
Build out resources that help someone doing a largely serverless deployment on GCP: pubsub, functions, databases, other services.

* [x] Firestore: explore as a filesystem (#577)
* [x] Cloud Functions: list, tail, delete (#578)
* [x] Pub/Sub: publish to topic, peek at topic traffic (#579)
* [x] Cloud Run: list, tail, delete (#612)

These are more ideas, will likely be delayed until we get more input on them
* Pub/Sub: subscriptions, peek at pulls by subscription
* Firestore: run query against collection. This optimizes filtering documents via `wash find`

**Comment by MikaelSmith** [comment]
For now we've only defined the first 3 items. We can define the rest as we finish up the initial items.

**Comment by MikaelSmith** [comment]
Pub/Sub subscriptions: not really feasible now that I understand how Pub/Sub works (topic sends to all subscriptions, multiple subscribers can pull from a single subscription to divide work).

Firestore run query we're putting off because we're having trouble with how to generalize it and it's not a principal feature, more of an improvement on how searching Firestore works.
