### ISSUE TITLE
Change `meta` attribute to partial metadata

### ISSUE THREAD

**Issue by ekinanp** [puppetlabs/wash#684]
This is basically removing https://github.com/puppetlabs/wash/blob/master/plugin/entryAttributes.go#L63 from EntryAttributes and moving it over to EntryBase as a `PartialMetadata` field. Reason for the change is b/c "partial" metadata makes a lot more sense, and is what we've been telling people anyways re: the `meta` attribute.

We'll also need to:

- [x] Update api with the changes
- [x] Update find's implementation
- [x] In external plugins, add `partial_metadata` key to entry JSON; change `meta_attribute_schema` => `partial_metadata_schema` in entry schema JSON.
- [x] Change `meta --attribute` => `meta --partial`. Update `info` and `docs`.
- [x] Update find's help text, especially the meta primary's.

AFTER RELEASE:
- [x] Update website with these changes. These include external plugin docs, blog posts, command documentation, tutorials etc. External plugin docs should highlight difference between partial metadata and metadata.
- [x] Update the wash-ruby gem, and any (known) deps. This is currently just puppetwash. We should also implement `write` for wash-ruby since we haven't done that yet.

**Comment by ekinanp** [comment]
This was done a while ago.
